version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    container_name: punktomat-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: dev.env

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: punktomat-frontend
    command: yarn serve
    depends_on:
      - db
      - backend
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - 8080:8080

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: punktomat-backend
    depends_on:
      - db
    volumes:
      - ./backend:/code
    ports:
      - 4000:4000
    env_file: dev.env

volumes:
  pgdata:
