version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: prod.env

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    depends_on:
      - db
      - backend
    volumes:
      - ./frontend:/code
    ports:
      - 80:80

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/code
    ports:
      - 4000:4000
    env_file: prod.env

volumes:
  pgdata:
