version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    container_name: punktomat-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env.dev

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: punktomat-backend
    depends_on:
      - db
    volumes:
      - ./backend:/code
    ports:
      - 4000:4000
    env_file: .env.dev

volumes:
  pgdata:
